### ISSUE TITLE
删除投票中的评论后，没有实时变化

### ISSUE THREAD

**Issue by shen100** [shen100/golang123#114]
![image](https://user-images.githubusercontent.com/2443162/32695408-cdc167c2-c795-11e7-9716-d9fad91ff5d2.png)

**Comment by thxallvu** [comment]
3个回复显示2个回复

**Comment by shen100** [comment]
@thxallvu  恩，我也发现了， 新开了个issue 
https://github.com/shen100/golang123/issues/115
