### ISSUE TITLE
ActiveSendMail 解析错误

### ISSUE THREAD

**Issue by 24** [shen100/golang123#150]
web  的verify/mail.vue 里面的request 发送email 的body的参数是email
```
    return request.sendmail({
                client: context.req,
                body: {
                    email: decodeURIComponent(query.e)
                }
```

but 
 
go  user/user.go  ActiveSendMail

``
if err := ctx.ReadJSON(&user); err != nil {
		SendErrJSON("参数无效", ctx)
		return
	}
	
```
是解析不粗来上面传递来的email参数 

因为   model/user.go 的email 的json体是空
```
    Pass           string             `json:"-"`
    Email          string             `json:"-"`

```
所以，有时候，他会获取不到这个email 的参数

也许 楼主这样 是为了防止隐私？？？

**Comment by shen100** [comment]
@24  已修复，谢谢反馈
