### ISSUE TITLE
如果有匿名发帖回复就好了

### ISSUE THREAD

**Issue by bfxyly** [shen100/golang123#151]
发现bbs很多，各个版本都好多，可就是偏偏千篇一律的功能，每一个bbs都不做匿名发帖的功能

**Comment by shen100** [comment]
@bfxyly  golang123未来会逐步增加独有的功能。
现在的投票功能，一般的BBS就没有哦，请尝试下
https://www.golang123.com/vote/2

匿名发帖的问题太多，如恶意发帖，发广告,  所以，不支持匿名发帖
