### ISSUE TITLE
网易 mail.yeah.net 邮箱注册无法接收验证码, 登录后的去邮箱验证按钮点击后打开页面错误.

### ISSUE THREAD

**Issue by ssoor** [shen100/golang123#154]
注册时使用 ******@yeah.net 邮箱, 邮箱无法接收到验证码.
登录后的邮箱验证页面中 去邮箱验证 按钮点击后打开的地址 http://mail. 不正确.
点击 重新发送 按钮后页面没有任何改变及响应, 不知是否设计如此.

**Comment by shen100** [comment]
@ssoor  已修复，请再试下，谢谢反馈
