### ISSUE TITLE
发现两个bug

### ISSUE THREAD

**Issue by thxallvu** [shen100/golang123#158]
1. 话题分类（标签、tag）目前应该只能是两个字，否则在文章页面会竖排，影响美观
如下图：
![2017-12-17 19-44-03](https://user-images.githubusercontent.com/32189272/34079227-48035dee-e364-11e7-8c2c-14acc0e96e39.png)

2. A发表一篇文章C，B评论A文章，A删除C，A的文章数减少，但是B的评论数不会减少。

**Comment by shen100** [comment]
已修复
1.改为如下的设计
![image](https://user-images.githubusercontent.com/2443162/34080608-fe43bd8a-e37b-11e7-8675-3f3574d0cb04.png)

2.作者删除自己的话题后，作者的话题数减少，但评论者的评论保留，同时显示原话题或投票被删除
![image](https://user-images.githubusercontent.com/2443162/34080419-927e2296-e378-11e7-9726-bebc1b3ad83a.png)
