### ISSUE TITLE
修改默认头像后，不显示

### ISSUE THREAD

**Issue by thxallvu** [shen100/golang123#161]
上传过程也没有提示错误，但是修改成功后空白。
![qq 20171219202326](https://user-images.githubusercontent.com/32189272/34157033-c0989f02-e4fa-11e7-9da9-1426b12cfa98.png)

**Comment by shen100** [comment]
@thxallvu 是用的最新的代码不？
还是UploadImgDir修改了没？如果修改了的话，请使用绝对路径，不要使用相对路径
![image](https://user-images.githubusercontent.com/2443162/34161628-2da81a08-e50c-11e7-9a9d-654410bbf716.png)

**Comment by thxallvu** [comment]
用的是最新的，我看是“如果要修改...” 这个路径我没有修改，现在保持空“”，但是/*图片上传的目录, 默认是golang123/website/static/upload/img目录*/   我看了这个static目录下没有upload目录

**Comment by shen100** [comment]
@thxallvu 
chmod 777 static,  然后再试下

**Comment by thxallvu** [comment]
@shen100 试了还是不行，我也试了 sudo chmod -R 777 static
