### ISSUE TITLE
server error, 当点击忘记密码后获取修改密码链接跳转后

### ISSUE THREAD

**Issue by gomaster-me** [shen100/golang123#216]
<img width="761" alt="4160f236-f53c-4f10-9a6d-e24e1acd8fb2" src="https://user-images.githubusercontent.com/5277544/36931331-825e6f36-1eee-11e8-8a27-5bfd088f6d22.png">

**Comment by gomaster-me** [comment]
<img width="761" alt="4160f236-f53c-4f10-9a6d-e24e1acd8fb2" src="https://user-images.githubusercontent.com/5277544/36931320-6e461ad0-1eee-11e8-857a-f1d29fc3befc.png">

**Comment by shen100** [comment]
@gomaster-me  已修复，感谢反馈
