### ISSUE TITLE
登陆后token未更新，请教一下你这边token是在哪进行更新的

### ISSUE THREAD

**Issue by Gtskk** [shen100/golang123#253]
登陆后token未更新，请教一下你这边token是在哪进行更新的

**Comment by Gtskk** [comment]
@shen100

**Comment by shen100** [comment]
@Gtskk  golang123/middleware/cookie.go

**Comment by Gtskk** [comment]
@shen100  我是说第一次登录，token怎么在客户端更新的

**Comment by Gtskk** [comment]
@shen100 我是说第一次登陆，客户端的token是如何更新的呢？

**Comment by Gtskk** [comment]
@shen100
