### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 756445638** [shen100/golang123#254]
npm install --registry=https://registry.npm.taobao.org  
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
Killed         ....] - extract:de-indent: sill gunzTarPerm modified mode [ 'dist/walk.es.js', 420, 436 ]

这个错误代表什么啊？？

**Comment by shen100** [comment]
什么系统？
WARN deprecated这个不要紧，只是库版本旧了，建议升级新版本
Killed通常是内存不够
