### ISSUE TITLE
注册账号signup页面404

### ISSUE THREAD

**Issue by walterliang** [shen100/golang123#267]
登陆、注册、重置密码发出的请求都是404
![image](https://user-images.githubusercontent.com/26303684/41198144-0649ccc4-6ca5-11e8-95af-03f79603a2c0.png)

**Comment by shen100** [comment]
配置nginx, 详见readme

http://localhost:8020/api/signup 这是错误的请求方式

访问
首页: https://dev.golang123.com
管理后台: https://dev.golang123.com/admin
用户名: golang123
密码: 123456 (登陆后请修改密码)
