### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by zztj** [shen100/golang123#272]
createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
看着是axios报的错，不知道什么原因。

**Comment by shen100** [comment]
请详细描述问题，最好有截图

**Comment by zztj** [comment]
![image](https://user-images.githubusercontent.com/15863306/42141054-e31cba6e-7dd8-11e8-8ebd-de0c29291075.png)

**Comment by zztj** [comment]
![image](https://user-images.githubusercontent.com/15863306/42141066-f630558e-7dd8-11e8-816e-349ffee1e30f.png)

**Comment by zztj** [comment]
我注册可以成功，但是登录总是失败，现在能访问到的页面都报这个错误。

**Comment by zztj** [comment]
配置了mongo连接后，不报错了，但时登录还是失败，也不报错。
