### ISSUE TITLE
伪开源

### ISSUE THREAD

**Issue by hdtopku** [shen100/golang123#334]
数据库啥的都不公开，怎么玩？

**Comment by Code2Life** [comment]
没仔细看作者的源码不， cfg.default.ts 的db配置，有个synchronize: false, 改成true就能自动创建db了

**Comment by Code2Life** [comment]
初始数据的脚本在 dbscripts里也有

**Comment by SuperHuangXu** [comment]
> 数据库啥的都不公开，怎么玩？

笑死。
