### ISSUE TITLE
golang123社区中文用户名无法注册，提示参数无效.

### ISSUE THREAD

**Issue by Yakumo-Yukari** [shen100/golang123#45]

**Comment by shen100** [comment]
@Yakumo-Yukari 我们这边测试是可以用中文注册的，请问您当时注册的中文名是什么？

**Comment by Yakumo-Yukari** [comment]
@shen100 我当时使用的中文用户名是  八雲紫 提示无效参数后来我以为是繁体的问题就换成了 八云紫 结果还是提示无效参数

**Comment by shen100** [comment]
用户名最少要4个字符，每个中文也当作一个字符
![image](https://user-images.githubusercontent.com/2443162/29831645-5d39bd2c-8d18-11e7-8812-9138b9557e83.png)

改成八云紫2 就注册成功了

![image](https://user-images.githubusercontent.com/2443162/29831620-45b6f142-8d18-11e7-9e82-487fc8d366de.png)
