### ISSUE TITLE
收藏相关问题

### ISSUE THREAD

**Issue by shen100** [shen100/golang123#83]
![7d23835b-19da-4489-a6e8-0fdc28deaacd](https://user-images.githubusercontent.com/2443162/30434842-d3b83792-999a-11e7-91d6-f641796bd420.png)

几条内容加上

**Comment by shen100** [comment]
![ccdf550a-1e81-4028-83dc-73a465719a11](https://user-images.githubusercontent.com/2443162/30434887-f579f15e-999a-11e7-99de-9c71aace5fe5.png)

改为收藏夹名称

**Comment by shen100** [comment]
![601ed8f1-85f0-466b-8b53-f556aa7556c1](https://user-images.githubusercontent.com/2443162/30434926-0c7c28f4-999b-11e7-96f7-7ab43eb634ea.png)

链接先去掉吧，将来要加的话，直接跳到 收藏夹页面，显示这个收藏夹下 收藏了哪些东西

**Comment by shen100** [comment]
![4f7f9ea0-4d56-4ad6-ae44-12c416a567b6](https://user-images.githubusercontent.com/2443162/30434949-22c8dd0a-999b-11e7-98ba-696b867ed99f.png)

几条内容加上

**Comment by shen100** [comment]
![94dbebe8-64dd-4234-a65c-fe78ceb79011](https://user-images.githubusercontent.com/2443162/30434969-2eccfd8e-999b-11e7-8d7e-cbb0c2bfce91.png)

鼠标滑过，照相机先隐藏

**Comment by shen100** [comment]
![4a5d9040-2e2d-427d-898b-a8a26464699d](https://user-images.githubusercontent.com/2443162/30434993-3af504e4-999b-11e7-827e-0b413b311a81.png)

删除没有调接口

**Comment by wanggz1992** [comment]
均已解决
