### ISSUE TITLE
我想拉下项目跑起来运行看看，现在node和go这边都缺少文件

### ISSUE THREAD

**Issue by liveshapps** [shen100/golang123#86]
大大，能不能把缺少的文件一并传上来呢?

**Comment by 24** [comment]
@liveshapps 
 
事实证明，一个文件都不缺。 💯

**Comment by Yakumo-Yukari** [comment]
不缺文件啊 我昨晚clone了下来 都跑起来了

**Comment by shen100** [comment]
@liveshapps  大家都说不缺文件呢， 我可以把go依赖的库的代码也一共提交, node依赖的模块要自己npm install
