### ISSUE TITLE
iris最新版context路径变化了，能否把依赖包govendor，然后提交下

### ISSUE THREAD

**Issue by chenxijunlove** [shen100/golang123#87]
能否把依赖包govendor，然后提交下，现在iris最新版context路径变化了，需要改很多代码

**Comment by shen100** [comment]
@chenxijunlove  golang123已将web框架切换到gin，使用dep来管理第三方包依赖，vendor目录已提交

**Comment by Zeno-Code** [comment]
@shen100 为啥换gin啦？

**Comment by shen100** [comment]
@Zeno-Code  gin的用户更多，接口更稳定，新的release不会破会已有的代码
